CREATE DATABASE	Artistas;

USE Artistas;

CREATE TABLE Artistas
(
	idArtista INT PRIMARY KEY IDENTITY
	,Nome VARCHAR (200) NOT NULL 
);

CREATE TABLE Estilos
(
	idEstilo INT PRIMARY KEY IDENTITY 
	,Nome VARCHAR (200) NOT NULL

);

CREATE TABLE Usuarios 
(
	idUsuario INT PRIMARY  KEY IDENTITY 
	,Nome	VARCHAR (200) NOT NULL
	,Email	VARCHAR (200) NOT NULL
	,Senha VARCHAR (200) NOT NULL 
	,Permissao	VARCHAR (200) NOT NULL
);

CREATE TABLE Albuns 
(
	idAlbum INT PRIMARY KEY IDENTITY 
	,idArtista INT FOREIGN KEY REFERENCES Artistas(idArtista)
	,Titulo VARCHAR (200) NOT NULL
	,dataLancamento	VARCHAR (200) NOT NULL
	,Localizacao	VARCHAR (200) NOT NULL
	,QuantidadeMinutos	VARCHAR (200) NOT NULL
	,Ativo	VARCHAR (200) NOT NULL 

);

CREATE TABLE AlbunsEstilos 
(
	idAlbum		INT PRIMARY KEY IDENTITY 
	,idEstilo	INT FOREIGN KEY REFERENCES Estilos (idEstilo)
);
