CREATE DATABASE Pessoas;

USE Pessoas;

CREATE TABLE Pessoas 
(
		idPessoa INT PRIMARY KEY IDENTITY
		,Nome		VARCHAR (100) NOT NULL
);

CREATE TABLE Telefones 
(
		idTelefones INT PRIMARY KEY IDENTITY,
		idPessoa	INT FOREIGN KEY REFERENCES Pessoas (idPessoa),
		Descricao	VARCHAR (150) NOT NULL 
);

CREATE TABLE Emails 
(
		idEmail INT PRIMARY KEY IDENTITY,
		idPessoa INT FOREIGN KEY REFERENCES  Pessoas (idPessoa),
		Descricao	VARCHAR (150) NOT NULL 
);

CREATE TABLE CNHs
(
		idCNH	INT PRIMARY KEY IDENTITY,
		idPessoa INT FOREIGN KEY REFERENCES Pessoas (idPessoa),
		Descricao VARCHAR (150) NOT NULL 
);